### ISSUE TITLE
Bug - cannot connect to Backoffice services on self-hosting ballerine

### ISSUE THREAD

**Issue by pratapalakshmi** [ballerine-io/ballerine#2089]
Upon deploying ballerine on ec2 instance. I tried accessing ballerine and i see the following. However, the same steps worked a week back

Back office:

![image](https://github.com/ballerine-io/ballerine/assets/137189067/5ccd9c76-7e71-4a93-935f-e7a53dceb229)

Workflow-dashboard:
<img width="1405" alt="image" src="https://github.com/ballerine-io/ballerine/assets/137189067/07d3a5a1-f6ce-4575-bdb3-a2da4480e538">

KYB-APP:

<img width="1356" alt="image" src="https://github.com/ballerine-io/ballerine/assets/137189067/33c222b7-5fbb-49c7-b699-53eb5a5aeb0d">

**Comment by ludmorales** [comment]
After using the latest Ballerine code (dev) with a domain/IP,   I have these messages/errors: 

**Collection Flow** 
![Screenshot 2024-02-19 at 19 22 34](https://github.com/ballerine-io/ballerine/assets/92339538/1a23d3e2-450b-4d0f-a35c-b7ed2b86691a)

**Case Management**
![Screenshot 2024-02-19 at 19 23 01](https://github.com/ballerine-io/ballerine/assets/92339538/7e3c60a2-f1e2-44d8-b7e3-ec47bcf45cd2)

**Monitoring Dashboard**
![Screenshot 2024-02-19 at 19 23 22](https://github.com/ballerine-io/ballerine/assets/92339538/983cabe7-b0f9-4436-9241-b291f694057e)

**Backend** 
I noted that is activated the https for the Backend :
![Screenshot 2024-02-19 at 19 23 52](https://github.com/ballerine-io/ballerine/assets/92339538/dd5c435f-b5e6-4cbb-b8d5-5d35d73d5d88)

**Comment by sarshad01** [comment]
Is there any progress on this? I have just setup the docker image and I have the same CORS error on all platforms

**Comment by WFA-juliver** [comment]
@sarshad01 @ludmorales experiencing that also but using ip only, cors pointing to localhost origin were resolved by updating envs on 

```
deploy/.env
apps/backoffice-v2/.env
apps/kyb-app/.env
apps/workflows-dashboard/.env

```
to container/server ip

but when attaching domain via nginx proxy, I'm receiving cors errors

**Comment by sarshad01** [comment]
@WFA-juliver @ludmorales I investigated it further and it seems like the CORS issue comes only from one service : workflows-service. The reason it appears is not actually related to origin, but because the container keeps restarting due to an error, here's the log of the workflows-service container

Loading environment variables from .env
2024-09-19T04:01:16.709400893Z Seeding database...
2024-09-19T04:01:16.820246687Z PrismaClientKnownRequestError: 
2024-09-19T04:01:16.820264094Z Invalid `prismaClient.workflowDefinition.create()` invocation in
2024-09-19T04:01:16.820266066Z /app/scripts/workflows/e2e-dynamic-url-example.ts:230:48
2024-09-19T04:01:16.820278334Z 
2024-09-19T04:01:16.820279501Z   227   isPublic: true,
2024-09-19T04:01:16.820280579Z   228 } as const satisfies Prisma.WorkflowDefinitionUncheckedCreateInput;
2024-09-19T04:01:16.820281748Z   229 export const generateDynamicDefinitionForE2eTest = async (prismaClient: PrismaClient) => {
2024-09-19T04:01:16.820283323Z → 230   return await prismaClient.workflowDefinition.create(
2024-09-19T04:01:16.820284803Z Unique constraint failed on the fields: (`id`)
2024-09-19T04:01:16.820286282Z     at Rn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:174:7325)
2024-09-19T04:01:16.820288449Z     at Rn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:174:6754)
2024-09-19T04:01:16.820290235Z     at Rn.request (/app/node_modules/@prisma/client/runtime/library.js:174:6344)
2024-09-19T04:01:16.820291719Z     at generateDynamicDefinitionForE2eTest (/app/scripts/workflows/e2e-dynamic-url-example.ts:230:10)
2024-09-19T04:01:16.820293641Z     at seed (/app/scripts/seed.ts:124:3) {
2024-09-19T04:01:16.820295070Z   code: 'P2002',
2024-09-19T04:01:16.820296561Z   clientVersion: '4.16.2',
2024-09-19T04:01:16.820298263Z   meta: { target: [ 'id' ] }
2024-09-19T04:01:16.820299711Z }
2024-09-19T04:01:16.987359840Z 
2024-09-19T04:01:16.987380613Z > @ballerine/workflows-service@0.7.38 prod
2024-09-19T04:01:16.987382323Z > npm run db:migrate-up && node dist/src/main
2024-09-19T04:01:16.987383606Z 
2024-09-19T04:01:17.135181090Z 
2024-09-19T04:01:17.135199662Z > @ballerine/workflows-service@0.7.38 db:migrate-up
2024-09-19T04:01:17.135201478Z > prisma migrate deploy
2024-09-19T04:01:17.135202843Z 
2024-09-19T04:01:17.368449126Z Prisma schema loaded from prisma/schema.prisma
2024-09-19T04:01:17.373842556Z Datasource "db": PostgreSQL database "postgres", schema "public" at "postgres:5432"
2024-09-19T04:01:17.407737430Z 
2024-09-19T04:01:17.407763142Z 80 migrations found in prisma/migrations
2024-09-19T04:01:17.407766264Z 
2024-09-19T04:01:17.420580934Z 
2024-09-19T04:01:17.420604533Z No pending migrations to apply.
2024-09-19T04:01:17.864012408Z Loading environment variables from .env
2024-09-19T04:01:19.041089841Z {"level":"info","logData":{},"message":"Listening on port 3000","timestamp":"2024-09-19T04:01:19.040Z"}
2024-09-19T04:01:19.060602548Z node:internal/process/promises:288
2024-09-19T04:01:19.060654474Z             triggerUncaughtException(err, true /* fromPromise */);
2024-09-19T04:01:19.060657281Z             ^
2024-09-19T04:01:19.060664112Z 
2024-09-19T04:01:19.060665874Z [Error: Invalid salt. Salt must be in the form of: $Vers$log2(NumRounds)$saltvalue]

**Comment by WFA-juliver** [comment]
> @WFA-juliver @ludmorales I investigated it further and it seems like the CORS issue comes only from one service : workflows-service. The reason it appears is not actually related to origin, but because the container keeps restarting due to an error, here's the log of the workflows-service container
> 
> Loading environment variables from .env 2024-09-19T04:01:16.709400893Z Seeding database... 2024-09-19T04:01:16.820246687Z PrismaClientKnownRequestError: 2024-09-19T04:01:16.820264094Z Invalid `prismaClient.workflowDefinition.create()` invocation in 2024-09-19T04:01:16.820266066Z /app/scripts/workflows/e2e-dynamic-url-example.ts:230:48 2024-09-19T04:01:16.820278334Z 2024-09-19T04:01:16.820279501Z 227 isPublic: true, 2024-09-19T04:01:16.820280579Z 228 } as const satisfies Prisma.WorkflowDefinitionUncheckedCreateInput; 2024-09-19T04:01:16.820281748Z 229 export const generateDynamicDefinitionForE2eTest = async (prismaClient: PrismaClient) => { 2024-09-19T04:01:16.820283323Z → 230 return await prismaClient.workflowDefinition.create( 2024-09-19T04:01:16.820284803Z Unique constraint failed on the fields: (`id`) 2024-09-19T04:01:16.820286282Z at Rn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:174:7325) 2024-09-19T04:01:16.820288449Z at Rn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:174:6754) 2024-09-19T04:01:16.820290235Z at Rn.request (/app/node_modules/@prisma/client/runtime/library.js:174:6344) 2024-09-19T04:01:16.820291719Z at generateDynamicDefinitionForE2eTest (/app/scripts/workflows/e2e-dynamic-url-example.ts:230:10) 2024-09-19T04:01:16.820293641Z at seed (/app/scripts/seed.ts:124:3) { 2024-09-19T04:01:16.820295070Z code: 'P2002', 2024-09-19T04:01:16.820296561Z clientVersion: '4.16.2', 2024-09-19T04:01:16.820298263Z meta: { target: [ 'id' ] } 2024-09-19T04:01:16.820299711Z } 2024-09-19T04:01:16.987359840Z 2024-09-19T04:01:16.987380613Z > @ballerine/workflows-service@0.7.38 prod 2024-09-19T04:01:16.987382323Z > npm run db:migrate-up && node dist/src/main 2024-09-19T04:01:16.987383606Z 2024-09-19T04:01:17.135181090Z 2024-09-19T04:01:17.135199662Z > @ballerine/workflows-service@0.7.38 db:migrate-up 2024-09-19T04:01:17.135201478Z > prisma migrate deploy 2024-09-19T04:01:17.135202843Z 2024-09-19T04:01:17.368449126Z Prisma schema loaded from prisma/schema.prisma 2024-09-19T04:01:17.373842556Z Datasource "db": PostgreSQL database "postgres", schema "public" at "postgres:5432" 2024-09-19T04:01:17.407737430Z 2024-09-19T04:01:17.407763142Z 80 migrations found in prisma/migrations 2024-09-19T04:01:17.407766264Z 2024-09-19T04:01:17.420580934Z 2024-09-19T04:01:17.420604533Z No pending migrations to apply. 2024-09-19T04:01:17.864012408Z Loading environment variables from .env 2024-09-19T04:01:19.041089841Z {"level":"info","logData":{},"message":"Listening on port 3000","timestamp":"2024-09-19T04:01:19.040Z"} 2024-09-19T04:01:19.060602548Z node:internal/process/promises:288 2024-09-19T04:01:19.060654474Z triggerUncaughtException(err, true /* fromPromise */); 2024-09-19T04:01:19.060657281Z ^ 2024-09-19T04:01:19.060664112Z 2024-09-19T04:01:19.060665874Z [Error: Invalid salt. Salt must be in the form of: $Vers$log2(NumRounds)$saltvalue]

same error on my end, I'm stuck on this part. I'm not sure how to fix this part, this shows upon logging the container `docker logs <workflow service>`, I followed the docker deployment documentation on a fresh server but unable to successfully deploy it, I hope we get response from the team.

**Comment by WFA-juliver** [comment]
any luck?
