### ISSUE TITLE
role "admin" does not exist PrismaClientInitializationError

### ISSUE THREAD

**Issue by daniGamium** [ballerine-io/ballerine#289]
### Description
I'm trying to install ballerine. `pnpm dev` works. However, whenever I try to install and do `pnpm kyc-manual-review-example` it tells me the error below. Any idea? I believe is something with my local postgres no having admin role, but how do I change that from the docker compose file?

`> ts-node scripts/clean.ts
Dropping all tables in the database...
2023-05-11 08:29:41.593 CEST [27735] FATAL:  role "admin" does not exist
PrismaClientInitializationError: 
Invalid `prisma.$queryRaw()` invocation:
User `admin` was denied access on the database `postgres.public`
    at pn.handleRequestError (/Users/danielsolerviladrich/Documents/GitHub/ballerine/node_modules/.pnpm/@prisma+client@4.13.0(prisma@4.13.0)/node_modules/@prisma/client/runtime/library.js:176:6750)
    at pn.handleAndLogRequestError (/Users/danielsolerviladrich/Documents/GitHub/ballerine/node_modules/.pnpm/@prisma+client@4.13.0(prisma@4.13.0)/node_modules/@prisma/client/runtime/library.js:176:5907)
    at /Users/danielsolerviladrich/Documents/GitHub/ballerine/node_modules/.pnpm/@prisma+client@4.13.0(prisma@4.13.0)/node_modules/@prisma/client/runtime/library.js:179:3087
    at /Users/danielsolerviladrich/Documents/GitHub/ballerine/node_modules/.pnpm/@prisma+client@4.13.0(prisma@4.13.0)/node_modules/@prisma/client/runtime/library.js:179:3294
    at Proxy._executeRequest (/Users/danielsolerviladrich/Documents/GitHub/ballerine/node_modules/.pnpm/@prisma+client@4.13.0(prisma@4.13.0)/node_modules/@prisma/client/runtime/library.js:179:10755)
    at Proxy._request (/Users/danielsolerviladrich/Documents/GitHub/ballerine/node_modules/.pnpm/@prisma+client@4.13.0(prisma@4.13.0)/node_modules/@prisma/client/runtime/library.js:179:10484)
    at getTables (/Users/danielsolerviladrich/Documents/GitHub/ballerine/services/workflows-service/scripts/clean.ts:41:8)
    at clean (/Users/danielsolerviladrich/Documents/GitHub/ballerine/services/workflows-service/scripts/clean.ts:18:18) {
  clientVersion: '4.13.0',
  errorCode: undefined
}
npm ERR! code ELIFECYCLE`
 

### Expected Behaviour
The installation proceed and two tabs open

### Actual Behaviour
Error above raises

### Environment
* Node version:
* Device, operating system and its version:
  *
* Browser and its version:
  *
* Version of the affected apps and packages:
  *

### Steps to Reproduce
1. Use a list format to describe which commands to run, and which actions to take.

### Any possible solutions
Describe the possible solutions you've considered, refer to files and lines of code when possible.

### If the bug is confirmed, would you be willing to submit a PR
(Y/N)

### Examples and references
Links, logs, screenshots, and other resources to help us understand the issue.

**Comment by alonp99** [comment]
@daniGamium , closing that for now, let us know if you need any additional help
